# Generated by Django 3.0.3 on 2020-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_fund_fundcommitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
