# Generated by Django 3.0.3 on 2020-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200224_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcommitment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
