# Generated by Django 3.0.3 on 2020-02-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200224_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundcommitment',
            old_name='Date',
            new_name='date',
        ),
    ]
