# Generated by Django 3.0.3 on 2020-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200224_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
