# Generated by Django 3.0.3 on 2020-02-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200224_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('invest_name', models.CharField(max_length=100)),
                ('capital_require', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='FundInvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.IntegerField()),
                ('invest_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Call')),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Fund')),
            ],
        ),
    ]
